

export const USER_COLLECTION_NAME = "USER-PERSONAL-INFORMATION";
export const USER_ORDERS_COLLECTION_NAME = "USER-ORDERS-HISTORY-INFORMATION";
export const USER_ADDRESS_COLLECTION_NAME = "USER-ADDRESS-INFORMATION";

// Product Category Collection Names
export const CLOTHING_COLLECTION_NAME = "CLOTHING-AND-ACCESSORIES-INFORMATION";

// Product Subcategory Collection Names (Clothing and Accessories)
export const TOPWEAR_SUBCOLLECTION_NAME = "TOPWEAR-AND-ACCESSORIES-INFORMATION";
export const BOTTOMWEAR_SUBCOLLECTION_NAME = "BOTTOMWEAR-AND-ACCESSORIES-INFORMATION";
export const FOOTWEAR_SUBCOLLECTION_NAME = "FOOTWEAR-AND-ACCESSORIES-INFORMATION";
export const WATCHES_SUBCOLLECTION_NAME = "WATCHES-AND-ACCESSORIES-INFORMATION";
export const WEAR_SUBCOLLECTION_NAME = "WEAR-AND-ACCESSORIES-INFORMATION";
export const WEAR_SUBCOLLECTION_NAME = "WEAR-AND-ACCESSORIES-INFORMATION";
export const WEAR_SUBCOLLECTION_NAME = "WEAR-AND-ACCESSORIES-INFORMATION";
export const WEAR_SUBCOLLECTION_NAME = "WEAR-AND-ACCESSORIES-INFORMATION";
export const WEAR_SUBCOLLECTION_NAME = "WEAR-AND-ACCESSORIES-INFORMATION";
