

export const USER_COLLECTION_NAME = "USER-PERSONAL-INFORMATION";
export const USER_ORDERS_COLLECTION_NAME = "USER-ORDERS-HISTORY-INFORMATION";
export const USER_ADDRESS_COLLECTION_NAME = "USER-ADDRESS-INFORMATION";
export const USER_PROMPT_COLLECTION_NAME = "USER-PROMPTS-INFORMATION";

// Product Category Collection Names 
export const TOPWEAR_COLLECTION_NAME = "TOPWEAR";
export const BOTTOMWEAR_COLLECTION_NAME = "BOTTOMWEAR";
export const FOOTWEAR_COLLECTION_NAME = "FOOTWEAR";
export const WATCHES_COLLECTION_NAME = "WATCHES";
export const BAGS_COLLECTION_NAME = "BAGS";
export const WINTERWEAR_COLLECTION_NAME = "WINTERWEAR";
export const ETHNICWEAR_COLLECTION_NAME = "ETHNICWEAR";

// Trending Fashion Trends Collection Names
export const TRENDS_COLLECTION_NAME = "FASHION-TRENDS-INFORMATION";
export const FASHION_TRENDS_KEY = "SOCIAL-MEDIA-FASHION-TRENDS";
export const TRENDING_INFLUENCERS_KEY = "TRENDING-INFLUENCERS";

// Product Sub-category Collection Names
export const TOPWEAR_TSHIRTS_COLLECTION_NAME = "TSHIRTS";
export const TOPWEAR_FORMAL_SHIRTS_COLLECTION_NAME = "FORMAL-SHIRTS";
export const TOPWEAR_CASUAL_SHIRTS_COLLECTION_NAME = "CASUAL-SHIRTS";

export const BOTTOMWEAR_JEANS_COLLECTION_NAME = "JEANS-SHIRTS";
export const BOTTOMWEAR_FORMAL_TROUSERS_COLLECTION_NAME = "FORMAL-TROUSERS";
export const BOTTOMWEAR_CASUAL_TROUSERS_COLLECTION_NAME = "CASUAL-TROUSERS";
export const BOTTOMWEAR_TRACK_PANTS_COLLECTION_NAME = "TRACK-PANTS-TROUSERS";
export const BOTTOMWEAR_SHORTS_COLLECTION_NAME = "SHORTS-TROUSERS";
export const BOTTOMWEAR_THREE_FOURTH_COLLECTION_NAME = "THREE-FOURTH-TROUSERS";

export const FOOTWEAR_SPORTS_SHOES_COLLECTION_NAME = "SPORTS-SHOES";
export const FOOTWEAR_CASUAL_SHOES_COLLECTION_NAME = "CASUAL-SHOES";
export const FOOTWEAR_FORMAL_SHOES_COLLECTION_NAME = "FORMAL-SHOES";
export const FOOTWEAR_SANDLES_AND_FLOATERS_COLLECTION_NAME = "SANDLES-AND-FLOATERS";
export const FOOTWEAR_FLIP_FLOPS_COLLECTION_NAME = "FLIP-FLOPS";
export const FOOTWEAR_LOAFERS_COLLECTION_NAME = "LOAFERS";
export const FOOTWEAR_BOOTS_COLLECTION_NAME = "BOOTS";
export const FOOTWEAR_RUNNING_SHOES_COLLECTION_NAME = "RUNNING-SHOES";
export const FOOTWEAR_SNEAKERS_COLLECTION_NAME = "SNEAKERS";

export const WATCHES_SPORTS_COLLECTION_NAME = "SPORTS-WATCHES";
export const WATCHES_ANALOG_COLLECTION_NAME = "ANALOG-WATCHES";
export const WATCHES_DIGITAL_COLLECTION_NAME = "DIGITAL-WATCHES";

export const BAGS_BAGPACKS_COLLECTION_NAME = "BAGPACKS";
export const BAGS_WALLETS_COLLECTION_NAME = "WALLETS";
export const BAGS_SUITCASE_COLLECTION_NAME = "SUITCASES";

export const WINTERWEAR_SWEATSHIRTS_COLLECTION_NAME = "SWEATSHIRTS";
export const WINTERWEAR_JACKETS_COLLECTION_NAME = "JACKETS";
export const WINTERWEAR_SWEATERS_COLLECTION_NAME = "SWEATERS";
export const WINTERWEAR_BLAZERS_COLLECTION_NAME = "BLAZERS";

export const ETHNICWEAR_KURTA_COLLECTION_NAME = "KURTA";
export const ETHNICWEAR_SHERWANI_COLLECTION_NAME = "SHERWANI";
export const ETHNICWEAR_DHOTI_COLLECTION_NAME = "DHOTI";
export const ETHNICWEAR_LUNGI_COLLECTION_NAME = "LUNGI";